# ロケール事前確認
- name: check locale
  shell: localectl status
  register: check_localectl_result
  check_mode: no
  changed_when: false

# ロケール設定
- name: set locale
  shell: localectl set-locale LANG=ja_JP.utf8
  when: "'LANG=ja_JP.utf8' not in check_localectl_result.stdout"

# タイムゾーン設定（タイムゾーンがUTCになっているのでJSTに変更）
- name: set timezone to Asia/Tokyo
  timezone:
    name: Asia/Tokyo

# パッケージアップデート
- name: apt update
  apt:
    update_cache: yes

- name: Add docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  become: yes

- name: Install basic packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - git
  become: yes

- name: Add apt repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
  become: yes

# パッケージインストール
- name: Install multi docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

# dockerサービスの起動
- name: start & enable docker service
  systemd:
    name: docker
    state: started
    enabled: yes

# docker-composeのインストール
- name: install docker-compose
  get_url:
    url:  "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64"
    dest: "/usr/bin/docker-compose"
    mode: +x

# git clone。このリポジトリをクローンしている
- name: git clone
  ansible.builtin.git:
    repo: https://github.com/yamadatt/ec2gitlab.git
    dest: /root/ec2gitlab

# gitlab-runnerをdockerグループに入れる
- name: Add gitlab-runner user to docker group
  user:
    name: gitlab-runner
    append: yes
    groups: docker

# gitlab runnerのインストール
- name: Install gitlab runner
  shell: |
    curl -LJO https://gitlab-runner-downloads.s3.amazonaws.com/latest/deb/gitlab-runner_amd64.deb
    dpkg -i gitlab-runner_amd64.deb
  args:
    creates: /usr/bin/gitlab-runner

- name: Register gitlab runner
  command: |
    gitlab-runner register \
    --non-interactive \
    --url "http://{{ ansible_host }}/" \
    --registration-token "{{ reg_token }}" \
    --executor "docker" \
    --docker-image alpine:latest \
    --description "docker-runner" \
    --tag-list "hugo" \
    --run-untagged="true"