name: AnsibleLint

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible==2.10 ansible-lint==4.3
    - name: Ansible Lint
      # working-directory: path/to/target_dir
      run: |
        ansible-lint --force-color -x 301,303,305

